### ISSUE TITLE
Import doesn't work

### ISSUE THREAD

**Issue by PolMrt** [appcoda/CreateMLQuickDemo#1]
Hi 👋
I want to import Create ML but it's not working : 
<img width="788" alt="capture d ecran 2018-06-08 a 18 56 09" src="https://user-images.githubusercontent.com/28253868/41170679-a680a23e-6b4d-11e8-9c4e-c6a129aafcff.png">

```
error: MyPlayground.playground:1:8: error: no such module 'CreateMLUI'
import CreateMLUI
       ^

error: MyPlayground.playground:3:8: error: no such module 'CreateML'
import CreateML
       ^
```
(i have macOs 10.14)

**Comment by simonng** [comment]
When creating the Playgrounds file, did you choose the Blank template under macOS tab?

**Comment by PolMrt** [comment]
I was running in iOs blank, but I have tried macOs blank and it's not working

**Comment by PolMrt** [comment]
Ok, found it ! I was saving the files in iCloud and apparently it doesn't work in iCloud, so I save in Desktop and it's working. Thank you !

**Comment by NickDatLe** [comment]
> Ok, found it ! I was saving the files in iCloud and apparently it doesn't work in iCloud, so I save in Desktop and it's working. Thank you !

This did not work for me.
